name: CI-CD for Iris ML Model 

on:
  push:
    branches:
      -master 
    
jobs:
  build-and-train:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt 

      - name: Train model 
        run: python example!_train.py 

      # - name: Run Flask server (test)
      #   run: |
      #     nohup python app.py &